config/routes.rb
Rails.application.routes.draw do

  namespace :tb_checkout, :path => '/' do

    get 'cart' => 'carts#show'
    resources :cart_items, :only => [:create, :update, :destroy]

    resources :transactions, :path => 'orders', :only => [:index, :show]
    resources :transactions, :path => 'checkout', :only => [:new, :create], :path_names => {:new => '/'}

    namespace :admin do
      resources :carts, :only => [:index, :show]
      resources :transactions, :only => [:index, :show]
    end
  end

end

app/models/tb_checkout/cart.rb
module TbCheckout
  class Cart < ActiveRecord::Base
    self.table_name = 'tb_checkout_carts'
    has_many :cart_items, :inverse_of => :cart
    has_many :transactions, :inverse_of => :cart

    scope :completed, ->{ where(:is_completed => true) }
    scope :in_progress, ->{ where(:is_completed => false, :is_abandoned => false) }
    scope :abandoned, ->{ where(:is_abandoned => true) }

    include TbCheckout::BelongsToUserSession

    # Look for carts that have outlived the configured TbCheckout.config.cart_lifespan value and mark them as abandoned
    #
    def self.check_abandoned!
      carts = in_progress.where('updated_at < ?', DateTime.now - TbCheckout.config.cart_lifespan)
      return carts.update_all(:is_abandoned => true)
    end

    # Build a short description of the cart contents
    #
    def description
      if cart_items.length == 0
        desc = "This cart is currently empty"
      elsif cart_items.length > 1
        desc = "#{cart_items.first.item_description} and #{cart_items.length-1} other #{'item'.pluralize(cart_items.length-1)}"
      else
        desc = cart_items.first.item_description
      end
      return desc
    end

    def total_price
      return self.cart_items.collect(&:total_price).sum()
    end

    def add_to_cart(product, quantity: 1)
      if !product.class.included_modules.map(&:to_s).include?("TbCheckout::Purchasable")
        raise ArgumentError, 'product must conform to TbCheckout::Purchasable'
      end
      return self.cart_items.create({
        :item => product,
        :quantity => quantity
      })
    end

    def is_empty?
      return self.cart_items.count == 0
    end

    def user_full_name
      return self.spud_user.try(:full_name) || 'Anonymous'
    end

  end
end

app/controllers/tb_checkout/admin/carts_controller.rb
class TbCheckout::Admin::CartsController < Admin::ApplicationController
  belongs_to_spud_app :shopping_carts
  before_action :setup_breadcrumb
  before_action :load_cart, :only => :show

  def index
    @carts = TbCheckout::Cart.order('created_at desc').includes(:cart_items).paginate(:page => params[:page])
    if params[:status]
      if params[:status] == 'completed'
        @carts = @carts.completed()
      elsif params[:status] == 'in-progress'
        @carts = @carts.in_progress()
      elsif params[:status] == 'abandoned'
        @carts = @carts.abandoned()
      end
    end
    respond_with @carts
  end

  def show
    respond_with @cart
  end

private

  def setup_breadcrumb
    add_breadcrumb 'Shopping Carts', tb_checkout_admin_carts_path(:status => params[:status])
  end

  def load_cart
    @cart = TbCheckout::Cart.where(:id => params[:id]).first
    if @cart.blank?
      flash[:error] = "Could not find the requested Shopping Cart"
      redirect_to tb_checkout_admin_carts_path
      return false
    end
  end

end

app/controllers/tb_checkout/carts_controller.rb
class TbCheckout::CartsController < TbCheckout::ApplicationController

  def show
    @cart = tb_checkout_current_cart
    respond_with @cart
  end

end

app/helpers/tb_checkout/admin/carts_helper.rb
module TbCheckout::Admin::CartsHelper

  def tb_checkout_status_label_for_cart(cart)
    if cart.is_completed?
      content_tag :span, 'Complete', :class => 'label label-success'
    elsif cart.is_abandoned?
      content_tag :span, 'Abandoned', :class => 'label label-inverse'
    else
      content_tag :span, 'In Progress', :class => 'label label-warning'
    end
  end

end

app/views/tb_checkout/admin/carts/index.html.erb
<% content_for :data_controls do %>
  <%= form_tag tb_checkout_admin_carts_path, :method => :get, :class => 'tb-checkout-cart-filter-form' do %>
  <%= select_tag :status, options_for_select([
    ['All', 'all'],
    ['Complete', 'completed'],
    ['In Progress', 'in-progress'],
    ['Abandoned', 'abandoned']
  ], params[:status]), :class => 'form-control' %>
  <% end %>
<% end %>

<% content_for :detail do %>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <th>User</th>
        <th>Description</th>
        <th>Total Price</th>
        <th>Status</th>
        <th>Last Modified</th>
        <th></th>
      </thead>
      <tbody>
        <% @carts.each do |cart| %>
          <tr>
            <td class="no-wrap"><%= cart.user_full_name %></td>
            <td><%= cart.description %></td>
            <td>
              <% if cart.is_empty? %>
                Empty
              <% else %>
                <%= number_to_currency cart.total_price %>
              <% end %>
            </td>
            <td>
              <%= tb_checkout_status_label_for_cart(cart) %>
            </td>
            <td class="no-wrap"><%= cart.updated_at.strftime('%I:%M %p, %D') %></td>
            <td>
              <%= link_to 'Detail', tb_checkout_admin_cart_path(cart, :status => params[:status]), :class => 'btn btn-sm btn-default' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= will_paginate @carts %>

  <script>
    $(document).ready(function(){
      $('.tb-checkout-cart-filter-form').on('change', 'select', function(e){
        $(this).parents('form').submit();
      });
    });
  </script>
<% end %>

app/views/tb_checkout/admin/carts/show.html.erb
<h3>General Info</h3>

<ul>
  <li><strong>User</strong> <%= @cart.user_full_name %></li>
  <li><strong>Created At</strong> <%= @cart.created_at.strftime('%I:%M %p, %D') %></li>
  <li><strong>Last Modified</strong> <%= @cart.updated_at.strftime('%I:%M %p, %D') %></li>
  <li><strong>Status</strong> <%= tb_checkout_status_label_for_cart(@cart) %></li>
</ul>

<h3>Products</h3>

<% if @cart.is_empty? %>
  <p>This cart does not contain any items.</p>
<% else %>
    <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
      </thead>
      <tbody>
        <% @cart.cart_items.each do |cart_item| %>
          <tr>
            <td><%= cart_item.item_description %></td>
            <td><%= cart_item.quantity %></td>
            <td><%= number_to_currency cart_item.total_price %></td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="2">Total</td>
          <td><%= number_to_currency @cart.total_price %></td>
        </tr>
      </tfoot>
    </table>
  </div>
<% end %>

<h3>Transactions</h3>

<% if @cart.transactions.blank? %>
  <p>There are no transactions associated with this shopping cart.</p>
<% else %>
  <%= render :partial => '/tb_checkout/admin/transactions/table', :locals => {:transactions => @cart.transactions} %>
<% end %>