config/routes.rb
Rails.application.routes.draw do

  namespace :tb_checkout, :path => '/' do

    get 'cart' => 'carts#show'
    resources :cart_items, :only => [:create, :update, :destroy]

    resources :transactions, :path => 'orders', :only => [:index, :show]
    resources :transactions, :path => 'checkout', :only => [:new, :create], :path_names => {:new => '/'}

    namespace :admin do
      resources :carts, :only => [:index, :show]
      resources :transactions, :only => [:index, :show]
    end
  end

end

app/models/concerns/tb_checkout/belongs_to_user_session.rb
module TbCheckout::BelongsToUserSession
  extend ActiveSupport::Concern

  included do
    belongs_to :spud_user
    validate :spud_user_id_is_not_zero
    validate :has_session_or_user_id
    validates :session_id, :presence => true

    # Return all records where the user matches
    # Should return zero results of the passed user is nil
    #
    scope :for_user, ->(user){
      if user.present?
        where(:spud_user => user)
      else
        none()
      end
    }

    # Return all records where the session_id matches
    # Should return zero results of the passed session_id is nil
    #
    scope :for_session, ->(session_id){
      if session_id.present?
        where(:session_id => session_id)
      else
        none()
      end
    }
  end

  def belongs_to?(user_id:nil, session_id:nil)
    return (self.session_id == session_id) || (self.spud_user_id.present? && self.spud_user_id != 0 && self.spud_user_id == user_id)
  end

private

  def spud_user_id_is_not_zero
    if spud_user_id == 0
      errors.add(:spud_user_id, 'cannot be 0')
    end
  end

  def has_session_or_user_id
    errors.add(:base, 'must have a user or session') if spud_user_id.blank? && session_id.blank?
  end

end

app/models/concerns/tb_checkout/purchasable.rb
module TbCheckout::Purchasable
  extend ActiveSupport::Concern

  included do
    has_many :cart_items, :class_name => 'TbCheckout::CartItem', :as => :item
    tb_checkout_quantity_is_editable(true)
    tb_checkout_delete_on_removal(false)

    include ActiveSupport::Callbacks
    define_callbacks :capture
    set_callback :capture, :after, :tb_checkout_after_capture!
  end

  module ClassMethods
    attr_reader :quantity_is_editable, :after_capture, :delete_on_removal, :url_builder, :cart_detail_view

    # Configure whether or not the given class of product should support multiple quantities
    # * Default: true
    #
    def tb_checkout_quantity_is_editable(is_editable)
      @quantity_is_editable = is_editable
    end

    # Configure a hook to run after the corresponding transaction is successfully captured
    # Use this to perform any cleanup tasks on the product model
    #
    # Ex:
    #   tb_checkout_after_capture ->(instance){
    #     instance.update_column(:is_captured, true)
    #   }
    #
    def tb_checkout_after_capture(symbol_or_lambda)
      @after_capture = symbol_or_lambda
    end

    # Configure whether or not the given class of product should self destruct when it is removed from the shopping cart
    # For example, this may make sense for a purchasable record that is only used one time
    # * Default: false
    #
    def tb_checkout_delete_on_removal(should_delete)
      @delete_on_removal = should_delete
    end

    # Configure a callback that builds a URL for the given product page
    # 
    # Ex:
    #   tb_checkout_url_builder ->(instance, context){
    #     context.widget_path(instance.id)
    #   }
    def tb_checkout_url_builder(symbol_or_lambda)
      @url_builder = symbol_or_lambda
    end

    # Configure a partial to be displayed in the shopping cart
    #
    def tb_checkout_cart_detail_view(detail_view)
      @cart_detail_view = detail_view
    end
  end

  def tb_checkout_build_url(view)
    url_builder = self.class.url_builder
    if url_builder.is_a? Proc
      return url_builder.call(self, view)
    elsif url_builder.is_a? Symbol
      return send(url_builder, view)
    end
  end

private

  def tb_checkout_after_capture!
    after_capture = self.class.after_capture
    if after_capture.is_a? Proc
      after_capture.call(self)
    elsif after_capture.is_a? Symbol  
      send(after_capture)
    end
  end

end

app/models/tb_checkout/basic_product.rb
module TbCheckout
  class BasicProduct < ActiveRecord::Base
    self.table_name = 'tb_checkout_basic_products'
    include TbCheckout::Purchasable
  end
end

app/models/tb_checkout/cart_item.rb
module TbCheckout
  class CartItem < ActiveRecord::Base
    self.table_name = 'tb_checkout_cart_items'
    belongs_to :cart, :inverse_of => :cart_items, :touch => true
    belongs_to :item, :polymorphic => true

    validates :cart, :item, :presence => true
    validates :quantity, :numericality => {:greater_than => 0}
    before_save :set_item_values
    after_destroy :cleanup_purchasable_item

    def total_price
      return item_price * quantity
    end

    def has_item_url?
      return self.item && self.item.class.url_builder.present?
    end

    def item_url(view)
      return item.tb_checkout_build_url(view)
    end

    def has_detail_view?
      return self.item && self.item.class.cart_detail_view.present?
    end

    def detail_view
      return self.item.class.cart_detail_view
    end

private

    def set_item_values
      if self.item
        self.item_description = self.item.description
        self.item_price = self.item.price
      end
    end

    def cleanup_purchasable_item
      if self.item && self.item.class.delete_on_removal
        self.item.destroy()
      end
    end

  end
end

app/controllers/concerns/tb_checkout/controller_helpers.rb
module TbCheckout::ControllerHelpers
  extend ActiveSupport::Concern

  included do
    helper_method :tb_checkout_current_cart
  end

  def tb_checkout_current_cart
    return nil unless session.id
    return TbCheckout::Cart.find_or_create_by({
      session_id: session.id,
      spud_user_id: current_user.try(:id),
      is_completed: false,
      is_abandoned: false
    })
  end

end

app/controllers/tb_checkout/admin/carts_controller.rb
class TbCheckout::Admin::CartsController < Admin::ApplicationController
  belongs_to_spud_app :shopping_carts
  before_action :setup_breadcrumb
  before_action :load_cart, :only => :show

  def index
    @carts = TbCheckout::Cart.order('created_at desc').includes(:cart_items).paginate(:page => params[:page])
    if params[:status]
      if params[:status] == 'completed'
        @carts = @carts.completed()
      elsif params[:status] == 'in-progress'
        @carts = @carts.in_progress()
      elsif params[:status] == 'abandoned'
        @carts = @carts.abandoned()
      end
    end
    respond_with @carts
  end

  def show
    respond_with @cart
  end

private

  def setup_breadcrumb
    add_breadcrumb 'Shopping Carts', tb_checkout_admin_carts_path(:status => params[:status])
  end

  def load_cart
    @cart = TbCheckout::Cart.where(:id => params[:id]).first
    if @cart.blank?
      flash[:error] = "Could not find the requested Shopping Cart"
      redirect_to tb_checkout_admin_carts_path
      return false
    end
  end

end

app/controllers/tb_checkout/admin/transactions_controller.rb
class TbCheckout::Admin::TransactionsController < Admin::ApplicationController
  belongs_to_spud_app :transactions
  add_breadcrumb 'Transactions', :tb_checkout_admin_transactions_path
  before_action :load_transaction, :only => :show

  def index
    @transactions = TbCheckout::Transaction.order('created_at desc').paginate(:page => params[:page])
    respond_with @transactions
  end

  def show
    respond_with @transaction
  end

private

  def load_transaction
    @transaction = TbCheckout::Transaction.where(:id => params[:id]).first
    if @transaction.blank?
      flash[:error] = 'Could not find the requested Transaction'
      redirect_to tb_checkout_admin_transactions_path
      return false
    end
  end

end

app/controllers/tb_checkout/application_controller.rb
module TbCheckout
  class ApplicationController < ::ApplicationController
    respond_to :html, :json
    layout TbCheckout.config.layout
  end
end

app/controllers/tb_checkout/cart_items_controller.rb
class TbCheckout::CartItemsController < TbCheckout::ApplicationController

  before_action :load_cart
  before_action :load_cart_item, :only => [:update, :destroy]

  def create
    @cart_item = @cart.cart_items.create(cart_item_params)
    respond_with @cart_item do |format|
      format.html{
        if @cart_item.errors.any?
          flash[:error] = "An error occurred: \"#{@cart_item.errors.full_messages.first}\""
          redirect_to :back
        else
          flash[:notice] = "Added \"#{@cart_item.item_description}\" to your cart"
          redirect_to tb_checkout_cart_path
        end
      }
    end
  end

  def update
    @cart_item.update_attributes(cart_item_params)
    respond_with @cart_item do |format|
      format.html{
        if @cart_item.errors.any?
          flash[:error] = "An error occurred: \"#{@cart_item.errors.full_messages.first}\""
          redirect_to :back
        else
          flash[:notice] = "Updated \"#{@cart_item.item_description}\" in your cart"
          redirect_to tb_checkout_cart_path
        end
      }
    end
  end

  def destroy
    @cart_item.destroy()
    respond_with @cart_item do |format|
      format.html{
        flash[:notice] = "Removed \"#{@cart_item.item_description}\" from your cart"
        redirect_to tb_checkout_cart_path
      }
    end
  end

private

  def load_cart
    @cart = tb_checkout_current_cart
  end

  def load_cart_item
    @cart_item = @cart.cart_items.where(:id => params[:id]).first
    if @cart_item.blank?
      raise Spud::NotFoundError('Cart Item')
    end
  end

  def cart_item_params
    params.require(:tb_checkout_cart_item).permit(:item_type, :item_id, :quantity)
  end

end

app/controllers/tb_checkout/carts_controller.rb
class TbCheckout::CartsController < TbCheckout::ApplicationController

  def show
    @cart = tb_checkout_current_cart
    respond_with @cart
  end

end

app/controllers/tb_checkout/transactions_controller.rb
class TbCheckout::TransactionsController < TbCheckout::ApplicationController

  before_action :load_cart, :only => [:new, :create, :confirm, :capture]

  def index
    @transactions = TbCheckout::Transaction.captured.includes(:cart => :cart_items).paginate(:page => params[:page], :per_page => 10)
    if current_user
      @transactions = @transactions.for_user(current_user)
    else
      @transactions = @transactions.for_session(session.id)
    end
    respond_with @transactions
  end

  def new
    @transaction = @cart.transactions.new()
    if !Rails.env.production?
      # These values will work against the Authorize.Net sandbox environment
      @transaction.card_type = 'visa'
      @transaction.card_number = 4007000000027
      @transaction.card_ccv = 123
      @transaction.card_expiration = Date.today.next_year
    end
  end

  def create
    @transaction = @cart.transactions.new(transaction_params)
    @transaction.session_id = session.id
    if @transaction.save() && @transaction.capture!
      flash[:notice] = 'Thanks! Your payment was collected successfully'
      redirect_to tb_checkout_transaction_path(@transaction)
    else
      if @transaction.response
        flash.now[:error] = @transaction.response.message
      end
      if @transaction.status == TbCheckout::Transaction::Status::FAIL
        @transaction = TbCheckout::Transaction.new(transaction_params)
      end
      render 'new'
    end
  end

  def show
    @transaction = TbCheckout::Transaction.captured.find_by(:id => params[:id])
    if @transaction.present? && @transaction.belongs_to?(user_id:current_user_id, session_id:session.id)
      render 'show'
    else
      flash[:error] = 'The transaction you were looking for could not be found'
      redirect_to tb_checkout_cart_path
    end
  end

private

  def transaction_params
    params.require(:tb_checkout_transaction).permit(:card_type, :card_number, :card_ccv, :card_expiration, 
      :billing_first_name, :billing_last_name, :billing_address_1, :billing_address_2, :billing_city, :billing_state, :billing_postal)
  end

  def load_cart
    @cart = tb_checkout_current_cart
    if @cart.blank? || @cart.is_empty?
      flash[:error] = 'You cannot check out with an empty cart'
      redirect_to tb_checkout_cart_path
      return false
    end
  end

end

app/helpers/tb_checkout/admin/carts_helper.rb
module TbCheckout::Admin::CartsHelper

  def tb_checkout_status_label_for_cart(cart)
    if cart.is_completed?
      content_tag :span, 'Complete', :class => 'label label-success'
    elsif cart.is_abandoned?
      content_tag :span, 'Abandoned', :class => 'label label-inverse'
    else
      content_tag :span, 'In Progress', :class => 'label label-warning'
    end
  end

end

app/helpers/tb_checkout/admin/transactions_helper.rb
module TbCheckout::Admin::TransactionsHelper

  def tb_checkout_status_label_for_transaction(status)
    if status == 'captured'
      cls = 'success'
    elsif status == 'fail'
      cls = 'danger'
    elsif status == 'refunded' || status == 'voided'
      cls = 'warning'
    else
      cls = 'default'
    end
    content_tag :span, status.titleize, :class => "label label-#{cls}"
  end

end

app/helpers/tb_checkout/application_helper.rb
module TbCheckout
  module ApplicationHelper

    # Return a link to the user's shopping cart, with the number of items in the text
    #
    # * link_text: The text of the link. Defaults: "My Cart"
    #
    def tb_checkout_cart_link(link_text:'My Cart')
      if tb_checkout_current_cart.present?
        count = tb_checkout_current_cart.cart_items.count
      else
        count = 0
      end
      link_to "#{link_text} (#{count})", tb_checkout_cart_path, :class => 'tb-checkout-cart-link'
    end

    # Return a form used to add a product to the user's shopping cart
    #
    # * product: The product you wish to add. Should be an ActiveRecord model that conforms to TbCheckout::Purchasable
    # * quantity: Whether to display a quantity picker. Defaults to false
    # * submit_text: Text of the submit button. Default: "Add to Cart"
    # * submit_class: CSS class of the submit button. Default: "btn btn-primary"
    # 
    def tb_checkout_add_to_cart(product, quantity: false, submit_text:'Add to Cart', submit_class:'btn btn-primary')
      cart_item = TbCheckout::CartItem.new({
        :item => product,
        :quantity => 1
      })
      return form_for cart_item, :html => {:class => 'tb-checkout-add-to-cart-form'} do |f|
        concat f.hidden_field :item_type
        concat f.hidden_field :item_id
        if quantity
          concat f.number_field :quantity, {:class => 'tb-checkout-add-to-cart-quantity'}
        else
          concat f.hidden_field :quantity
        end
        concat f.submit submit_text, :class => "#{submit_class} tb-checkout-add-to-cart-submit"
      end
    end

    # Return a list of states for use in a form select field
    #
    def tb_checkout_options_for_states()
      us_states = [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
      ]
      if TbCheckout.config.canada_is_real
        return {
          'United States' => us_states,
          'Canada' => [
            ['Alberta', 'AB'],
            ['British Columbia ', 'BC'],
            ['Manitoba', 'MB'],
            ['New Brunswick', 'NB'],
            ['Newfoundland and Labrador', 'NL'],
            ['Nova Scotia', 'NS'],
            ['Northwest Territories', 'NT'],
            ['Nunavut', 'NU'],
            ['Ontario', 'ON'],
            ['Prince Edward Island', 'PE'],
            ['Quebec', 'QC'],
            ['Saskatchewan', 'SK'],
            ['Yukon', 'YT']
          ]
        }
      else
        return us_states
      end
    end

    # Return a list of credit card types for use with a form select
    #
    def tb_checkout_credit_card_types()
      types = [
        ['Visa', 'visa'],
        ['MasterCard', 'master'],
        ['Discover', 'discover'],
        ['American Express', 'american_express']
      ]
      types.select!{ |a, b|
        TbCheckout.config.card_types.include?(b.to_sym)
      }
      return types
    end

  end
end

app/helpers/tb_checkout/transactions_helper.rb
module TbCheckout::TransactionsHelper
end

app/views/tb_checkout/transactions/_details.html.erb
<h4>Credit Card</h4>
<dl class="dl-horizontal tb-checkout-transaction-confirm-info">
  <dt>Number</dt>
  <dd><%= @transaction.card_display %></dd>
  <dt>Type</dt>
  <dd><%= @transaction.card_type.titleize %></dd>
  <dt>Amount Charged</dt>
  <dd><%= number_to_currency @transaction.amount_charged %></dd>
</dl>

<h4>Billing Address</h4>
<dl class="dl-horizontal tb-checkout-transaction-confirm-info">
  <dt>Name</dt>
  <dd><%= @transaction.billing_full_name %></dd>
  <dt>Address</dt>
  <dd><%= @transaction.billing_full_address %></dd>
</dl>

app/views/tb_checkout/transactions/index.html.erb
<h1>My Orders</h1>

<table class="table tb-checkout-transactions-table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Card</th>
      <th>Amount</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% cache @transactions do %>
      <% @transactions.each do |transaction| %>
        <% cache transaction do %>
          <tr>
            <td><%= transaction.created_at.strftime('%D') %></td>
            <td><%= transaction.cart.description %></td>
            <td><%= transaction.card_display %> (<%= transaction.card_type.titleize %>)</td>
            <td><%= number_to_currency transaction.amount_charged %></td>
            <td><%= link_to 'Details', tb_checkout_transaction_path(transaction) %>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= will_paginate @transactions %>

app/views/tb_checkout/transactions/new.html.erb
<h1>Check Out</h1>

<%= render :partial => '/tb_checkout/carts/cart', :locals => {:editable => false, :cart => @cart} %>

<h2>Billing Info</h2>

<%= form_for @transaction, :url => new_tb_checkout_transaction_path, :html => {:class => 'tb-checkout-checkout-form form-horizontal'} do |f| %>

  <%= tb_form_errors(@transaction) %>

  <div class="form-group">
    <%= f.label :card_type, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.select :card_type, tb_checkout_credit_card_types, {}, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :card_number, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :card_number, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :card_expiration, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.date_select :card_expiration, {:discard_day => true, :start_year => Date.today.year, :end_year => Date.today.year+10}, {:class => 'form-control form-control-date-select'} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :card_ccv, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :card_ccv, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :billing_first_name, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :billing_first_name, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :billing_last_name, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :billing_last_name, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :billing_address_1, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :billing_address_1, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :billing_city, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :billing_city, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :billing_state, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.select :billing_state, tb_checkout_options_for_states, {:prompt => 'Select State'}, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :billing_postal, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :billing_postal, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group form-actions">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Submit', :class => 'btn btn-primary', :data => {:disable_with => 'Please wait...'} %>
      <%= link_to 'Back', tb_checkout_cart_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tb_checkout/transactions/show.html.erb
<h1>Invoice</h1>

<p>Print this page for your records.</p>

<h4>Your Order</h4>
<%= render :partial => '/tb_checkout/carts/cart', :locals => {:editable => false, :cart => @transaction.cart} %>

<%= render 'details' %>

<p><%= link_to 'View My Orders', tb_checkout_transactions_path %></p>