config/routes.rb
Rails.application.routes.draw do

  namespace :tb_checkout, :path => '/' do

    get 'cart' => 'carts#show'
    resources :cart_items, :only => [:create, :update, :destroy]

    resources :transactions, :path => 'orders', :only => [:index, :show]
    resources :transactions, :path => 'checkout', :only => [:new, :create], :path_names => {:new => '/'}

    namespace :admin do
      resources :carts, :only => [:index, :show]
      resources :transactions, :only => [:index, :show]
    end
  end

end

app/controllers/tb_checkout/admin/transactions_controller.rb
class TbCheckout::Admin::TransactionsController < Admin::ApplicationController
  belongs_to_spud_app :transactions
  add_breadcrumb 'Transactions', :tb_checkout_admin_transactions_path
  before_action :load_transaction, :only => :show

  def index
    @transactions = TbCheckout::Transaction.order('created_at desc').paginate(:page => params[:page])
    respond_with @transactions
  end

  def show
    respond_with @transaction
  end

private

  def load_transaction
    @transaction = TbCheckout::Transaction.where(:id => params[:id]).first
    if @transaction.blank?
      flash[:error] = 'Could not find the requested Transaction'
      redirect_to tb_checkout_admin_transactions_path
      return false
    end
  end

end

app/controllers/tb_checkout/transactions_controller.rb
class TbCheckout::TransactionsController < TbCheckout::ApplicationController

  before_action :load_cart, :only => [:new, :create, :confirm, :capture]

  def index
    @transactions = TbCheckout::Transaction.captured.includes(:cart => :cart_items).paginate(:page => params[:page], :per_page => 10)
    if current_user
      @transactions = @transactions.for_user(current_user)
    else
      @transactions = @transactions.for_session(session.id)
    end
    respond_with @transactions
  end

  def new
    @transaction = @cart.transactions.new()
    if !Rails.env.production?
      # These values will work against the Authorize.Net sandbox environment
      @transaction.card_type = 'visa'
      @transaction.card_number = 4007000000027
      @transaction.card_ccv = 123
      @transaction.card_expiration = Date.today.next_year
    end
  end

  def create
    @transaction = @cart.transactions.new(transaction_params)
    @transaction.session_id = session.id
    if @transaction.save() && @transaction.capture!
      flash[:notice] = 'Thanks! Your payment was collected successfully'
      redirect_to tb_checkout_transaction_path(@transaction)
    else
      if @transaction.response
        flash.now[:error] = @transaction.response.message
      end
      if @transaction.status == TbCheckout::Transaction::Status::FAIL
        @transaction = TbCheckout::Transaction.new(transaction_params)
      end
      render 'new'
    end
  end

  def show
    @transaction = TbCheckout::Transaction.captured.find_by(:id => params[:id])
    if @transaction.present? && @transaction.belongs_to?(user_id:current_user_id, session_id:session.id)
      render 'show'
    else
      flash[:error] = 'The transaction you were looking for could not be found'
      redirect_to tb_checkout_cart_path
    end
  end

private

  def transaction_params
    params.require(:tb_checkout_transaction).permit(:card_type, :card_number, :card_ccv, :card_expiration, 
      :billing_first_name, :billing_last_name, :billing_address_1, :billing_address_2, :billing_city, :billing_state, :billing_postal)
  end

  def load_cart
    @cart = tb_checkout_current_cart
    if @cart.blank? || @cart.is_empty?
      flash[:error] = 'You cannot check out with an empty cart'
      redirect_to tb_checkout_cart_path
      return false
    end
  end

end

app/helpers/tb_checkout/admin/transactions_helper.rb
module TbCheckout::Admin::TransactionsHelper

  def tb_checkout_status_label_for_transaction(status)
    if status == 'captured'
      cls = 'success'
    elsif status == 'fail'
      cls = 'danger'
    elsif status == 'refunded' || status == 'voided'
      cls = 'warning'
    else
      cls = 'default'
    end
    content_tag :span, status.titleize, :class => "label label-#{cls}"
  end

end

app/helpers/tb_checkout/transactions_helper.rb
module TbCheckout::TransactionsHelper
end

app/views/tb_checkout/admin/transactions/_table.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <th>Transaction ID</th>
      <th>Billing Name</th>
      <th>Card</th>
      <th>Amount Charged</th>
      <th>Date</th>
      <th>Status</th>
      <th></th>
    </thead>
    <tbody>
      <% transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.gateway_transaction_id %></td>
          <td class="no-wrap"><%= transaction.billing_full_name %></td>
          <td class="no-wrap"><%= transaction.card_display %> (<%= transaction.card_type %>)</td>
          <td><%= number_to_currency transaction.amount_charged %></td>
          <td><%= transaction.created_at.strftime('%D %-l:%M %p') %></td>
          <td><%= tb_checkout_status_label_for_transaction(transaction.status) %></td>
          <td><%= link_to 'Detail', tb_checkout_admin_transaction_path(transaction), :class => 'btn btn-sm btn-default' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tb_checkout/admin/transactions/index.html.erb
<% content_for :data_controls do %>

<% end %>

<% content_for :detail do %>
  <%= render :partial => 'table', :locals => {:transactions => @transactions} %>
  <%= will_paginate @transactions, :renderer => BootstrapPagination::Rails %>
<% end %>

app/views/tb_checkout/admin/transactions/show.html.erb
<h3>Summary</h3>
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>User</th>
        <th>Invoice Number</th>
        <th>Transaction ID</th>
        <th>Card</th>
        <th>Amount Charged</th>
        <th>Date</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <td><%= @transaction.cart.user_full_name %></td>
      <td><%= @transaction.invoice_num %></td>
      <td><%= @transaction.gateway_transaction_id %></td>
      <td><%= @transaction.card_display %> (<%= @transaction.card_type %>)</td>
      <td><%= number_to_currency @transaction.amount_charged %></td>
      <td><%= @transaction.created_at.strftime('%D %-l:%M %p') %></td>
      <td><%= tb_checkout_status_label_for_transaction(@transaction.status) %></td>
    </tbody>
  </table>
</div>

<h3>Billing Address</h3>
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Address 2</th>
        <th>City</th>
        <th>State</th>
        <th>Postal</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @transaction.billing_full_name %></td>
        <td><%= @transaction.billing_address_1 %></td>
        <td><%= @transaction.billing_address_2 || "--" %></td>
        <td><%= @transaction.billing_city %></td>
        <td><%= @transaction.billing_state %></td>
        <td><%= @transaction.billing_postal %></td>
      </tr>
  </table>
</tbody>

<h3>Line Items</h3>
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @transaction.cart.cart_items.each do |cart_item| %>
        <tr>
          <td><%= cart_item.item_description %></td>
          <td><%= cart_item.quantity %></td>
          <td><%= number_to_currency cart_item.total_price %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2">Total</td>
        <td><%= number_to_currency @transaction.cart.total_price %></td>
      </tr>
    </tfoot>
  </table>
</div>

<h3>API Response Text</h3>

<%= debug @transaction.response_json %>